HadithSearch/Controllers/AuthenticiteController.cs
using HadithSearch.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;


namespace HadithSearch.Controllers
{
    public class AuthenticiteController : Controller
    {
        DB_HADITHSEARCHEntities db = new DB_HADITHSEARCHEntities();

        // GET: Authenticite
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult AjouterAuthenticite()
        {
            try
            {
                ViewBag.listeAuthenticite = db.AUTHENTICITE.ToList();

                return View();
            }
            catch (Exception e)
            {
                return HttpNotFound();
            }
        }


        [HttpPost]
        public ActionResult AjouterAuthenticite(AUTHENTICITE authenticite)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    db.AUTHENTICITE.Add(authenticite);
                    db.SaveChanges();
                }
                return RedirectToAction("AjouterAuthenticite");
            }
            catch (Exception e)
            {
                return HttpNotFound();
            }
        }
    }
}

HadithSearch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom d'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Auteur", "AjoutAuteur", "Auteur")</li>
                    <li>@Html.ActionLink("Recueil", "AjouterRecueil", "Recueil")</li>
                    <li>@Html.ActionLink("Chapitre", "AjouterChapitre", "Chapitre")</li>
                    <li>@Html.ActionLink("Transmetteur", "AjouterTransmetteur", "Transmetteur")</li>
                    <li>@Html.ActionLink("Hadith", "AjouterHadith", "Hadith")</li>
                    <li>@Html.ActionLink("Authenticité", "AjouterAuthenticite", "Authenticite")</li>


                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>